# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sandhya Venkataramaiah"
resume_title:                   "Master's in Computer Student at Vanderbilt UNiversity"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sandhya.venkataramaiah@vanderbilt.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "669(287)-8646"
resume_contact_address:         "Nashville, Tennesse"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>As an experienced candidate and dedicated master's student, I am actively seeking a challenging internship opportunity where I can apply my academic knowledge and acquired practical experience in the field of Software Development. Possessing a solid skill set that includes Angular, Node.js, Express.js, RESTful API Design, HTML/CSS, MySQL, MsSQL, JavaScript, Java, Typescript and Python, I am enthusiastic about joining a dynamic team to contribute my expertise and continuous to enhance my professional skills through practical, real-world experience.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/sandhya-va"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/sandhya-venkataramaiah-4165b628a/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
